
## DRUG_EXPOSURE

### source.{source_table} (BRONZE)

Structured data sources for medications prescribing and dispensing will generally always include:

| Table                                  | Type            |
|----------------------------------------|-----------------|
| Electronic prescribing and administration                | Legacy + Live          |
| Pharmacy dispensing | Legacy + Live          |

Tables are loaded to the database in batches, or through incremental ingestion via connection to a source database.

### bronze.base_ or stg_{source}__{entity} (BRONZE)

Data sources are staged as `stg_{source}__{entity}` (if necessary, with an initial step of `base_{source}__{entity}` prior to unioning). This may include column renaming and edge case handling.

### silver.int_drug_exposure_dispensing (SILVER)

Different data sources are UNIONED into a common dataset for representing medications that are dispensed from pharmacy to inpatient, outpatient, and to-take-away. This table does not contain data from specialty specific systems such as chemotherapy.

Patients must first be assigned a `person_uuid`. Where dispensing is attached to a particular hospital admission or attendance, these `spells` or `attendances` must first be assigned a `visit_occurrence_id`.

The column `drug_type` helps interpretation, and will indirectly map to OMOP drug_type_concept_id:
- `dispensing_unknown` indicates a drug that was ordered for dispensing from pharmacy, but the data source does not provide information to indicate whether this dispensing was carried out;
- `dispensing_dispensed` indicates a drug that was ordered and dispensed to patient from pharmacy;
- `dispensing_notdispensed` indicates a drug that was ordered for dispensing, but ultimately not dispensed.

This table gives flexibility for highly detailed source systems, including possiblities for recording formulations and prescribed doses and instructions for each drug.

```{mermaid}
---
title: Drug Exposure (Dispensing) Intermediate Table
---
erDiagram
    int_drug_exposure_dispensing {
        drug_occurrence_id integer "[PK] autogenerated identifier"
        person_uuid uuid "[FK mrt_person] standardised unique person id"
        drug_exposure_start_date date
        drug_exposure_start_datetime timestamp
        drug_exposure_end_date date
        drug_exposure_end_datetime timestamp        
        drug_source_value varchar "drug code as represented in source"
        drug_source_value_name varchar "drug name as represented in source - may include formulation"
        domain_id varchar "most relevant omop domain"
        source_vocabulary_id varchar "id of source vocab"
        drug_type varchar "status of drug, dispensing_unknown, dispensing_dispensed, dispensing_notdispensed"
        drug_location varchar "free text for location context - e.g. ward name, or inpatient, outpatient, TTA"
        drug_desc varchar "additional free text for further qualification, e.g. resupply, new supply"
        route_source_value varchar "route as represented in the source"
        item_formulation_source_value varchar "if available, best string that fully describes the item, e.g. 500mg tablet"
        item_strength_quantity_source_value varchar "strength of one item of drug e.g. 500"
        item_strength_units_source_value varchar "units given to one item e.g. mg"        
        item_type_source_value varchar "type of item, e.g. tablet"
        dose_instruct_source_value varchar "if available, best string that captures dosing instructions, e.g. 1g four times a day"
        dose_quantity_source_value varchar "dose prescribed e.g. 1"
        dose_unit_source_value varchar "units given to the prescribed dose e.g. g"
        dose_frequency_source_value varchar "dosing instructions e.g. four times a day"
        days_supply integer "how many days given"
        stop_reason varchar "stop reason where given in source"
        sig varchar "additional verbatim instructions for drug"
        visit_occurrence_id integer "[FK mrt_visit_occurrence] standardised unique visit id"
        source_table_provenance varchar "source table name"
        source_row_id uuid "unique row id for the single concept that is generated at ingestion"
    }
```

### silver.int_drug_exposure_prescribing (SILVER)

Different data sources are UNIONED into a common dataset for representing medications that are prescribed +/- administered while attending a hospital location. This table does not contain data from specialty specific systems such as chemotherapy.

Patients must first be assigned a `person_uuid`. Where dispensing is attached to a particular hospital admission or attendance, these `spells` or `attendances` must first be assigned a `visit_occurrence_id`.

The column `drug_type` helps interpretation, and will indirectly map to OMOP drug_type_concept_id:
- `prescribing_unknown` indicates a drug that was prescribed, but the data source does not provide information to indicate whether the drug was administered or not
- `prescribing_administered` indicates that a drug was prescribed and administered to the patient
- `presribing_notadministered` indicates that a drug was prescribed but was explicitly cancelled or otherwise not given

This table also gives flexiblity for inputting special prescription/administration types, such as infusions.
```{mermaid}
---
title: Drug Exposure (Prescribing) Intermediate Table
---
erDiagram
    int_drug_exposure_prescribing {
        drug_occurrence_id integer "[PK] autogenerated identifier"
        person_uuid uuid "[FK mrt_person] standardised unique person id"
        drug_exposure_start_date date
        drug_exposure_start_datetime timestamp
        drug_exposure_end_date date
        drug_exposure_end_datetime timestamp        
        drug_source_value varchar "drug code as represented in source"
        drug_source_value_name varchar "drug name as represented in source - may include formulation"
        domain_id varchar "most relevant omop domain"
        source_vocabulary_id varchar "id of source vocab"
        drug_type varchar "status of drug, prescribing_unknown, prescribing_administered, prescribing_notadministered"
        drug_location varchar "free text for location context - e.g. ward name or clinic name"
        drug_desc varchar "additional free text for further qualification, e.g. patient refused"
        route_source_value varchar "route as represented in the source"
        item_formulation_source_value varchar "best string that fully describes item, particularly infusions: e.g. 10mg/ml propofol emulsion"       
        item_type_source_value varchar "type of item, e.g. emulsion"        
        dose_instruct_source_value varchar "best string that captures dosing, e.g. 100mg"
        dose_quantity_source_value varchar "dose prescribed e.g. 100"
        dose_unit_source_value varchar "units given to the prescribed dose e.g. mg"
        dose_frequency_source_value varchar "dosing instructions e.g. once stat"
        infusion_rate_source_value varchar "rate of infusion between start_datetime and end_datetime"
        infusion_rate_quantity_source_value float "rate of infusion as number"
        infusion_rate_unit_source_value varchar "rate of infusion units"
        stop_reason varchar "stop reason where given in source"
        sig varchar "additional verbatim instructions for drug"
        visit_occurrence_id integer "[FK mrt_visit_occurrence] standardised unique visit id"
        source_table_provenance varchar "source table name"
        source_row_id uuid "unique row id for the single concept that is generated at ingestion"
    }
```


### silver.mrt_drug_exposure (SILVER)

This is the transformed version of ingested drug_exposure tables.  Concepts in this table are mapped to OMOP standards, and column naming is compatible, but it contains the following differences:

- Standardised concept codes/names are surfaced, and indexed, to enable user-friendly exploration and visualisation without the need for large joins;
- OMOP CDM 5.4 columns that are not relevant to the NHS, or to intended purposes, are excluded. When converting to vanilla OMOP, these columns remain empty;
- Source, table, and systems provenance are maintained, and closest provenance type is mapped to `drug_type_concept_id` per OMOP.

...


### OMOP CDM 5.4 - OMOP.DRUG_EXPOSURE
This table captures records about the exposure to a Drug ingested or otherwise introduced into the body. A Drug is a biochemical substance formulated in such a way that when administered to a Person it will exert a certain biochemical effect on the metabolism. Drugs include prescription and over-the-counter medicines, vaccines, and large-molecule biologic therapies. Radiological devices ingested or applied locally do not count as Drugs.
```{mermaid}
---
title: OMOP.DRUG_EXPOSURE
---
erDiagram
    DRUG_EXPOSURE {
        drug_exposure_id integer "[PK not null] autogenerated identifier"
        person_id integer "[FK not null]"
        drug_concept_id integer "[not null] standard OMOP concept id used for analyses, contains strength/dose info"
        drug_exposure_start_date date "[not null]"
        drug_exposure_start_datetime timestamp
        drug_exposure_end_date date "[not null]"
        drug_exposure_end_datetime timestamp
        verbatim_end_date date
        drug_type_concept_id integer "[not null] e.g. prescriptions / dispensed / patient reported"
        stop_reason varchar20 "reason for stopping as per source"
        refills integer
        quantity float "any numerical value for amount of drug"
        days_supply integer
        sig varcharMAX "verbatim instructions for drug"
        route_concept_id integer "standard omop concept id in route domain"
        lot_number varchar50
        provider_id integer "[FK] clinician provider who recorded condition"
        visit_occurrence_id integer "[FK]"
        visit_detail_id integer "[FK]"
        drug_source_value varchar50 "drug code as represented in source"
        drug_source_concept_id integer "source mapped to omop but often left empty"
        route_source_value varchar50 "verbatim route given in source"
        dose_unit_source_value varchar50 "verbatim units given in source"
    }
```

### IMPLEMENTATION - SILVER.DRUG_EXPOSURE

SILVER.DRUG_EXPOSURE is the cleaned and transformed version of ingested drug prescription, administration and/or dispensing tables, that are used to stage vanilla OMOP CDM 5.4 tables (as well as other GOLD transformations). This table is wider than the OMOP data model, and includes the following differences:

- Standardised concept codes/names are surfaced, and indexed, to enable user-friendly exploration and visualisation without the need for large joins;
- Source concept codes/names are surfaced to enable direct visibility over semantic provenance;
- Dose information from source NHS inpatient drug adminstration systems (or 'drug charts') are difficult to represent unambiguously in OMOP. For example, OMOP quantity may contain 'number of tablets' OR 'dose' OR 'total dosage given'. In the NHS, administration records found in drug charts are often a drug name (e.g. Paracetamol) and a dose (e.g. 1g) without any information about medication formulation or strength, which is the preferred information held in a standard OMOP concept. SILVER.DRUG_EXPOSURE therefore explicitly differentiates between item strength and quantity, and prescribed/administered dose.
- SILVER.DRUG_EXPOSURE also includes a column to indicate whether a prescribed dose was administered at the time, or if the dose was 'not given' at the prescribed time. 
- Each row holds information about a single concept relative to a single person. We can therefore incorporate additional, NHS-specific, information about table and systems provenance relative to source data. By extension, this allows for additional understanding of context of data generation, whereas it is often necessary to infer 'OMOP drug type'.
- OMOP CDM 5.4 columns that are not relevant to the NHS, or to intended purposes, are initialised, but set as null, and remain empty when carried into OMOP.

```{mermaid}
---
title: SILVER.DRUG_EXPOSURE
---
erDiagram
    DRUG_EXPOSURE {
        drug_exposure_id integer "[PK not null] autogenerated identifier"
        person_id integer "[FK not null]"
        drug_concept_id integer "[not null] standard OMOP concept id used for analyses, contains strength/dose info"
        drug_concept_code varchar50 "[NEW] standard OMOP concept code"
        drug_concept_name varcharMAX "[NEW] standard OMOP concept name"
        drug_concept_vocabulary_id varchar20 "[FK NEW] OMOP vocabulary id representing the standard concept"        
        drug_exposure_start_date date "[not null]"
        drug_exposure_start_datetime timestamp
        drug_exposure_end_date date "[not null]"
        drug_exposure_end_datetime timestamp
        verbatim_end_date date "[set as null]"
        drug_type_concept_id integer "[not null] e.g. prescriptions / dispensed / patient reported"
        stop_reason varchar20 "[set as null]"
        refills integer "[set as null]"
        quantity float "any numerical value for amount of drug"
        quantity_type varchar50 "[NEW] indicates what type of quantity is indicated"
        quantity_unit varchar50 "[NEW] clean version of unit for the quantity"
        dose_administration_flag varchar50 "[NEW] for EPMA, indicates whether the drug was administered (yes/no/na)"        
        days_supply integer "[set as null]"
        sig varcharMAX "[set as null]"
        route_concept_id integer "standard omop concept id in route domain"
        lot_number varchar50 "[set as null]"
        provider_id integer "[set as null]"
        visit_occurrence_id integer "[FK]"
        visit_detail_id integer "[set as null]"
        drug_source_value varchar50 "drug code as represented in source"
        drug_source_value_name varcharMAX "[NEW] drug name as represented in source"        
        drug_source_concept_id integer "[set as null]"
        dose_source_value float "[NEW] verbatim drug dose for each administration given in source"
        dose_unit_source_value varchar50 "verbatim units given in source"
        route_source_value varchar50 "verbatim route given in source"
        source_system_provenance varchar50 "[NEW] name of specific system from which source table was ingested"
        source_table_provenance varchar50 "[NEW] source table name"
        source_row_id varchar50 "[NEW] unique row id for the single concept that is generated at ingestion"        
    }
```


### ADDITIONAL NOTES

None for now!

### OUTSTANDING ISSUES

None for now!

### VERSION TRACKING

_JZ 2024-July-15_: initial version, loaded original omop table and suggested SILVER model.