
## PERSON

### source.{source_table} (BRONZE)

Structured data sources for person and core demographic information will generally always include:

| Table                                  | Type            |
|----------------------------------------|-----------------|
| Commissioning Datasets                 | Legacy          |
| Patient Information Management Systems | Legacy          |
| Electronic Health Record patient index | Live / ADT feed |
| Individual Observations / Facts        | Legacy + Live   |

Tables are loaded to the database in batches, or through incremental ingestion via connection to a source database. 

### bronze.base_ or stg_{source}__{entity} (BRONZE)

Data sources are staged as `stg_{source}__{entity}` (if necessary, with an initial step of `base_{source}__{entity}` prior to unioning). This may include column renaming and edge case handling.

### silver.int_person_identifier_lookup (SILVER)

Due to the large number of patient identification systems found in any hospital, and the possibility of patient ID duplication (and subsequent deduplication), we normalise all identifiers (including hospital IDs, NHS numbers, specific system IDs) under a `person_uuid` that we generate. Note that while NHS numbers are often seen as a canonical identifier, these exhibit significant missingness either due to failure to retrieve from NHS Spine, or because a patient is not registered in the NHS.

```{mermaid}
---
title: Person Identifier Lookup Table
---
erDiagram
    int_person_identifier_lookup {
        person_uuid uuid "generated for each unique person"
        patient_id varchar "patient identifier from source systems"
        patient_id_type varchar "type of patient identifier"
        valid_from date "date of record creation"
        valid_to date "date of record deprecation (e.g. if lookup no longer valid)"
    }
```

### silver.int_person_birth, silver.int_person_gender, silver.int_person_ethnicity (SILVER)

The source tables which contain patient demographics are a combination of normalised tables, and flat / wide tables, and may be maintained as type 1 or 2 SCD. We normalise patient characteristics found in these tables to enable visibility over changing and/or conflicting information (data handling decisions are pushed to a later stage).

Normalised tables handle core characteristics, that we treat as patient dimensions.

```{mermaid}
---
title: Person Intermediate Tables
---
erDiagram
    int_person_birth {
        person_uuid uuid "[PK] generated for each unique person"
        year_of_birth integer "[not null]"
        month_of_birth integer
        day_of_birth integer
        birth_datetime timestamp
        source_table_provenance varchar50 "source table name"
        source_row_id uuid "unique row id for the single concept that is generated at ingestion"
    }
    int_person_birth ||--|{ int_person_gender : "has gender"
    int_person_gender {
        person_uuid uuid "[FK] int_person_birth"
        gender_source_value varchar "gender code from source system"
        gender_source_value_name varchar "gender descriptive name from source system"        
        gender_type varchar "type of gender (e.g. Epic - phenotypic)"
        domain_id varchar "constrained by possible omop domains"
        source_vocabulary_id varchar "id of source vocab"        
        source_table_provenance varchar "source table name"
        source_row_id uuid "unique row id for the single concept that is generated at ingestion"
        date_valid date "date of record creation"
        date_invalid date "date of record deprecation (e.g. if data item no longer valid)"
    }
    int_person_birth ||--|{ int_person_ethnicity : "has ethnicity"
    int_person_ethnicity {
        person_uuid uuid "[FK] int_person_birth"
        ethnicity_source_value varchar20 "ethnicity code from source system"
        ethnicity_source_value_name varchar20 "ethnicity descriptive name from source system"
        domain_id varchar "constrained by possible omop domains"
        source_vocabulary_id varchar "id of source vocab"                   
        source_table_provenance varchar50 "source table name"
        source_row_id uuid "unique row id for the single concept that is generated at ingestion"
        date_valid date "date of record creation"
        date_invalid date "date of record deprecation (e.g. if data item no longer valid)"
    }
```

### SILVER - silver.int_person_deprivation

Deprivation is derived from patient postcode. The remaining parts of address are discarded.

```{mermaid}
---
title: Person Intermediate Table (Deprivation)
---
erDiagram
    int_person_birth {
        person_uuid uuid "[PK] generated for each unique person"
        year_of_birth integer
        month_of_birth integer
        day_of_birth integer
        birth_datetime timestamp
        source_table_provenance varchar "source table name"
        source_row_id uuid "unique row id for the single concept that is generated at ingestion"
    }
    int_person_birth ||--|{ int_person_deprivation : "has deprivation"
        int_person_deprivation {
        person_uuid uuid "[FK] int_person_birth"
        postcode varchar "postcode with space"
        deprivation_decile integer "derived from postcode lookup"        
        index_multiple_deprivation integer "ranked IMD from postcode lookup"
        source_table_provenance varchar "source table name"
        source_row_id uuid "unique row id for the single concept that is generated at ingestion"
        valid_from date "date of record creation"
        valid_to date "date of record deprecation (e.g. if data item no longer valid)"
    }
```

### silver.mrt_person (SILVER)

This is the transformed version of ingested person and demographic tables. This table is wider than the OMOP data model can be further constrained to transform into vanilla OMOP. It contains the following differences from OMOP:

- Standardised concept codes/names are surfaced, and indexed, to enable user-friendly exploration and visualisation without the need for large joins;
- Additional demographic fields for UK specific deprivation are included; 
- OMOP CDM 5.4 columns that are not relevant to the NHS, or to intended purposes, are initialised, but we do not populate. They remain empty when carried into omop.person;
- To populate this, logic is applied to surface the most recent and reliable dimensions based on intermediate tables.    

```{mermaid}
---
title: OMOP-EXT Person
---
erDiagram
    mrt_person {
        person_uuid uuid "[PK] generated for each unique person"
        gender_concept_id integer "[OMOP, not null] standard omop concept"
        gender_concept_code varchar "standard concept code"
        gender_concept_name varchar "standard concept name"
        year_of_birth integer "[OMOP, not null]"
        month_of_birth integer "[OMOP]"
        day_of_birth integer "[OMOP]"
        birth_datetime timestamp "[OMOP]"
        race_concept_id integer "[OMOP, not null] ethnicity in NHS"
        race_concept_code varchar "standard concept code"
        race_concept_name varchar "standard concept name"      
        deprivation_decile_as_number integer "NHS IMD decile"       
        deprivation_index_as_number integer "NHS IMD ranking"
        ethnicity_concept_id integer "[OMOP] not populated"
        location_id integer "[OMOP] not populated"
        provider_id integer "[OMOP] not populated"
        care_site_id integer "[OMOP] not populated"
        person_source_value varchar "[OMOP] we populate with nhs number where available"
        gender_source_value varchar "[OMOP] we populate with source code"
        gender_source_concept_id integer "[OMOP] not populated"
        race_source_value varchar "[OMOP] we populate with source code"
        race_source_concept_id integer "[OMOP] not populated"
        ethnicity_source_value varchar "[OMOP] not populated"
        ethnicity_source_concept_id integer "[OMOP] not populated"   
    }
```

### omop.person (GOLD, OMOP CDM 5.4)

Central identity management for all persons in the OMOP data model. It contains records that uniquely identify each person or patient, and some demographic information. The canonical OMOP table is shown below. 
```{mermaid}
---
title: OMOP Person Table
---
erDiagram
    person {
        person_id integer "[PK not null]"
        gender_concept_id integer "[not null]"
        year_of_birth integer "[not null]"
        month_of_birth integer
        day_of_birth integer
        birth_datetime timestamp
        race_concept_id integer "[not null] race or ethnicity"
        ethnicity_concept_id integer "[not null] US-specific hispanic vs non-hispanic"
        location_id integer "patient physical address"
        provider_id integer "GP who is primary care provider"
        care_site_id integer "GP surgery for primary care"
        person_source_value varchar50 "nhs number where available"
        gender_source_value varchar50 "biological sex as represented in source"
        gender_source_concept_id integer "mapping to omop, but often empty"
        race_source_value varchar50 "race or ethnicity as represented in source"
        race_source_concept_id integer "mapping to omop, but often empty"
        ethnicity_source_value varchar50 "US-specific as represented in source"
        ethnicity_source_concept_id integer "mapping to omop, but often empty"
    }
```
